keystore = "/home/johnzampolin/gorc/keystore/"

[gravity]
contract = "0x4d9f727c3a49cF36721E35F4576F901A632eE2e6"
fees_denom = "usomm"

[ethereum]
key_derivation_path = "m/44'/60'/0'/0/0"
rpc = "http://localhost:8545"

[cosmos]
key_derivation_path = "m/44'/118'/0'/0/0"
grpc = "http://localhost:9090"
prefix = "cosmos"
