keystore = "/home/ubuntu/gorc/keystore/"

[gravity]
contract = "0xE049479156eC5Facc052E780Aeee70122b10d5d3"
fees_denom = "usomm"

[ethereum]
key_derivation_path = "m/44'/60'/0'/0/0"
rpc = "http://localhost:8545"

[cosmos]
key_derivation_path = "m/44'/118'/0'/0/0"
grpc = "http://localhost:9090"
prefix = "cosmos"
