keystore = "/home/ubuntu/gorc/keystore/" #edit this value for what it is your sommelier v2 gorc

[gravity]
contract = "0x69592e6f9d21989a043646fE8225da2600e5A0f7" 
fees_denom = "usomm"

[ethereum]
key_derivation_path = "m/44'/60'/0'/0/0"
rpc = "http://localhost:8545" #Can use alchemy or infura here.
gas_price_multiplier = 1.0
blocks_to_search = 5000

[cosmos]
key_derivation_path = "m/44'/118'/0'/0/0"
grpc = "http://localhost:9090"
prefix = "somm"
gas_adjustment = 1.0
msg_batch_size = 5

[cosmos.gas_price]
amount = 0.000
denom = "usomm"

[metrics]
listen_addr = "127.0.0.1:3000"